#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# Définition d'une route pour une page d'accueil
#index:
 # path: /
 # controller: App\Controller\ChequeController::index
 # methods: GET

# Définition d'une route avec un paramètre
cheque_signature:
  path: /api_public/v3/signature_request/{signatureRequestId}/signer
  controller: App\Controller\ChequeController::signature
  methods: POST