#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# config/routes.yaml

like_article:
    path: '/article/{id}/like'
    controller: 'App\Controller\ArticleController::like'
    methods: ['POST']

dislike_article:
    path: '/article/{id}/dislike'
    controller: 'App\Controller\ArticleController::dislike'
    methods: ['POST']

save_article:
    path: '/article/{id}/save'
    controller: 'App\Controller\ArticleController::save'
    methods: ['POST']
